name: Run tests

jobs:
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java
      with:
        java-version: '17'
    - name: Run Gradle Tests
      run: ./gradlew test
